// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcox_MH
List rcox_MH(int n, NumericVector win, List snfield, int iter, int dbg);
RcppExport SEXP rcox_rcox_MH(SEXP nSEXP, SEXP winSEXP, SEXP snfieldSEXP, SEXP iterSEXP, SEXP dbgSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type win(winSEXP );
        Rcpp::traits::input_parameter< List >::type snfield(snfieldSEXP );
        Rcpp::traits::input_parameter< int >::type iter(iterSEXP );
        Rcpp::traits::input_parameter< int >::type dbg(dbgSEXP );
        List __result = rcox_MH(n, win, snfield, iter, dbg);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
