# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_lambda_c <- function(snfield, x) {
    .Call('_rcox_evaluate_lambda_c', PACKAGE = 'rcox', snfield, x)
}

rcox_MH <- function(n, win, snfield, iter, dbg) {
    .Call('_rcox_rcox_MH', PACKAGE = 'rcox', n, win, snfield, iter, dbg)
}

rcox_thin <- function(win, snfield, dbg) {
    .Call('_rcox_rcox_thin', PACKAGE = 'rcox', win, snfield, dbg)
}

