# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcox_MH <- function(n, win, snfield, iter, dbg) {
    .Call('rcox_rcox_MH', PACKAGE = 'rcox', n, win, snfield, iter, dbg)
}

